llmctx(1)

# NAME

llmctx - convert the content of a directory into context for LLMs

# SYNOPSIS

*llmctx* [OPTIONS]... FILES

# DESCRIPTION

*llmctx* is a stupid simple and easy-to-use command-line utility that allows you
to easily and recursively convert the contents of directories into text that can
be used as context by large language models such as ChatGPT.

# OPTIONS

*-i*, *--input*
	The directory to convert.

*-o*, *--output*
	The file to write the context to.

*-h*, *--help*
	Show help message and quit.

*-v*, *--version*
	Show version number and quit.

# AUTHORS

Maintained by James Pond <james@cipher.host>.
